import { createRouter, createWebHistory } from 'vue-router';
import HomePage from '../views/HomePage.vue';
import ToolsList from '../components/ToolsList.vue';

const routes = [
  { path: '/', name: 'HomePage', component: HomePage },
  { path: '/ToolsList', name: 'ToolsList', component: ToolsList },
  { path: '/html-markdown-converter', name: 'HtmlMarkdownConverter', component: () => import('@/components/HtmlMarkdownConverter.vue') },
  { path: '/csv-json-converter', name: 'CsvJsonConverter', component: () => import('@/components/CsvJsonConverter.vue') },
  { path: '/base64-encoder-decoder', name: 'Base64EncoderDecoder', component: () => import('@/components/Base64EncoderDecoder.vue') },
  { path: '/url-encoder-decoder', name: 'UrlEncoderDecoder', component: () => import('@/components/UrlEncoderDecoder.vue') },
  { path: '/hex-rgb-converter', name: 'HexRgbConverter', component: () => import('@/components/HexRgbConverter.vue') },
  { path: '/html-entities-encoder-decoder', name: 'HtmlEntitiesEncoderDecoder', component: () => import('@/components/HtmlEntitiesEncoderDecoder.vue') },
  { path: '/binary-text-converter', name: 'BinaryTextConverter', component: () => import('@/components/BinaryTextConverter.vue') },
  { path: '/text-ascii-converter', name: 'TextAsciiConverter', component: () => import('@/components/TextAsciiConverter.vue') },
  { path: '/epoch-time-converter', name: 'EpochTimeConverter', component: () => import('@/components/EpochTimeConverter.vue') },
  { path: '/html-php-converter', name: 'HtmlPhpConverter', component: () => import('@/components/HtmlPhpConverter.vue') },
  { path: '/meta-tags-generator', name: 'Meta Tags Generator', component: () => import('@/components/MetaTagsGenerator.vue') },
  { path: '/robots-txt-generator', name: 'Robots.txt Generator', component: () => import('@/components/RobotsTxtGenerator.vue') },
  { path: '/sitemap-generator', name: 'Sitemap Generator', component: () => import('@/components/SitemapGenerator.vue') },
  { path: '/lorem-ipsum-generator', name: 'Lorem Ipsum Generator', component: () => import('@/components/LoremIpsumGenerator.vue') },
  { path: '/password-generator', name: 'Password Generator', component: () => import('@/components/PasswordGenerator.vue') },
  { path: '/uuid-generator', name: 'UUID Generator', component: () => import('@/components/UuidGenerator.vue') },
  { path: '/qr-code-generator', name: 'QR Code Generator', component: () => import('@/components/QrCodeGenerator.vue') },
  { path: '/barcode-generator', name: 'Barcode Generator', component: () => import('@/components/BarcodeGenerator.vue') },
  { path: '/image-placeholder-generator', name: 'Image Placeholder Generator', component: () => import('@/components/PlaceholderImageGenerator.vue') },
  { path: '/box-shadow-generator', name: 'CSS Box Shadow Generator', component: () => import('@/components/BoxShadowGenerator.vue') },
  { path: '/gradient-generator', name: 'CSS Gradient Generator', component: () => import('@/components/GradientGenerator.vue') },
  { path: '/border-radius-generator', name: 'CSS Border Radius Generator', component: () => import('@/components/BorderRadiusGenerator.vue') },
  { path: '/flexbox-generator', name: 'CSS Flexbox Generator', component: () => import('@/components/FlexboxGenerator.vue') },
  { path: '/color-palette-generator', name: 'Color Palette Generator', component: () => import('@/components/ColorPaletteGenerator.vue') },
  { path: '/rgb-to-hsl-converter', name: 'RGB to HSL Converter', component: () => import('@/components/RgbToHslConverter.vue') },
  { path: '/favicon-generator', name: 'Favicon Generator', component: () => import('@/components/FaviconGenerator.vue') },
  { path: '/open-graph-tags-generator', name: 'Open Graph Tags Generator', component: () => import('@/components/OpenGraphTagsGenerator.vue') },
  { path: '/social-media-preview-card-generator', name: 'Social Media Preview Card Generator', component: () => import('@/components/SocialMediaPreviewCardGenerator.vue') },
  { path: '/fake-data-generator', name: 'Fake Data Generator', component: () => import('@/components/FakeDataGenerator.vue') },
  { path: '/utm-link-generator', name: 'UTM Link Generator', component: () => import('@/components/UtmLinkGenerator.vue') },
  { path: '/whois-lookup', name: 'Whois Lookup', component: () => import('@/components/WhoisLookup.vue') },
  { path: '/dns-lookup', name: 'DNS Lookup', component: () => import('@/components/DnsLookup.vue') },
  { path: '/reverse-dns-lookup', name: 'Reverse DNS Lookup', component: () => import('@/components/ReverseDnsLookup.vue') },
  { path: '/ip-geolocation', name: 'IP Geolocation', component: () => import('@/components/IpGeolocation.vue') },
  { path: '/ssl-certificate-checker', name: 'SSL Certificate Checker', component: () => import('@/components/SslCertificateChecker.vue') },
  { path: '/http-header-checker', name: 'HTTP Header Checker', component: () => import('@/components/HttpHeaderChecker.vue') },
  { path: '/page-speed-tester', name: 'Page Speed Tester', component: () => import('@/components/PageSpeedTester.vue') },
  { path: '/domain-age-checker', name: 'Domain Age Checker', component: () => import('@/components/DomainAgeChecker.vue') },
  { path: '/http-status-checker', name: 'HTTP Status Code Checker', component: () => import('@/components/HttpStatusChecker.vue') },
  { path: '/browser-info', name: 'Browser Information Lookup', component: () => import('@/components/BrowserInfoLookup.vue') },
  { path: '/html-validator', name: 'HTML Validator', component: () => import('@/components/HtmlValidator.vue') },
  { path: '/css-validator', name: 'CSS Validator', component: () => import('@/components/CssValidator.vue') },
  { path: '/json-validator', name: 'JSON Validator', component: () => import('@/components/JsonValidator.vue') },
  { path: '/javascript-validator', name: 'JavaScript Code Validator', component: () => import('@/components/JavascriptValidator.vue') },
  { path: '/xml-validator', name: 'XML Validator', component: () => import('@/components/XmlValidator.vue') },
  { path: '/email-validator', name: 'Email Address Validator', component: () => import('@/components/EmailValidator.vue') },
  { path: '/url-validator', name: 'URL Validator', component: () => import('@/components/UrlValidator.vue') },
  { path: '/schema-validator', name: 'Schema Markup Validator', component: () => import('@/components/SchemaValidator.vue') },
  { path: '/accessibility-checker', name: 'Accessibility Checker (WCAG Compliance)', component: () => import('@/components/AccessibilityChecker.vue') },
  { path: '/html-minifier', name: 'HTML Minifier/Unminifier', component: () => import('@/components/HtmlMinifier.vue') },
  { path: '/css-minifier', name: 'CSS Minifier/Unminifier', component: () => import('@/components/CssMinifier.vue') },
  { path: '/js-minifier', name: 'JavaScript Minifier/Unminifier', component: () => import('@/components/JsMinifier.vue') },
  { path: '/json-formatter', name: 'JSON Minifier/Prettifier', component: () => import('@/components/JsonFormatter.vue') },
  { path: '/html-formatter', name: 'HTML Formatter', component: () => import('@/components/HtmlFormatter.vue') },
  { path: '/css-formatter', name: 'CSS Formatter', component: () => import('@/components/CssFormatter.vue') },
  { path: '/js-formatter', name: 'JavaScript Formatter', component: () => import('@/components/JsFormatter.vue') },
  { path: '/sql-formatter', name: 'SQL Formatter', component: () => import('@/components/SqlFormatter.vue') },
  { path: '/python-formatter', name: 'Python Formatter', component: () => import('@/components/PythonFormatter.vue') },
  { path: '/php-formatter', name: 'PHP Formatter', component: () => import('@/components/PhpFormatter.vue') },
  { path: '/keyword-density-checker', name: 'Keyword Density Checker', component: () => import('@/components/KeywordDensityChecker.vue') },
  { path: '/seo-analyzer', name: 'SEO Title & Description Analyzer', component: () => import('@/components/SeoAnalyzer.vue') },
  { path: '/serp-preview-tool', name: 'SERP Preview Tool', component: () => import('@/components/SerpPreviewTool.vue') },
  { path: '/redirect-checker', name: 'Redirect Checker', component: () => import('@/components/RedirectChecker.vue') },
  { path: '/broken-link-checker', name: 'Broken Link Checker', component: () => import('@/components/BrokenLinkChecker.vue') },
  { path: '/website-uptime-checker', name: 'Website Uptime Checker', component: () => import('@/components/WebsiteUptimeChecker.vue') },
  { path: '/content-word-counter', name: 'Content Word Counter', component: () => import('@/components/ContentWordCounter.vue') },
  { path: '/backlink-checker', name: 'Backlink Checker', component: () => import('@/components/BacklinkChecker.vue') },
  { path: '/password-hash-generator', name: 'Password Hash Generator', component: () => import('@/components/PasswordHashGenerator.vue') },
  { path: '/xss-vulnerability-tester', name: 'XSS Vulnerability Tester', component: () => import('@/components/XSSVulnerabilityTester.vue') },
  { path: '/csrf-token-generator', name: 'CSRF Token Generator', component: () => import('@/components/CSRFTokensGenerator.vue') },
  { path: '/secure-token-generator', name: 'Secure Token Generator', component: () => import('@/components/SecureTokenGenerator.vue') },
  { path: '/key-pair-generator', name: 'Public Key/Private Key Generator', component: () => import('@/components/KeyPairGenerator.vue') },
  { path: '/image-aio-tool', name: 'Image AIO Tool', component: () => import('@/components/ImageAIOTool.vue') },
  { path: '/exif-data-viewer', name: 'EXIF Data Viewer', component: () => import('@/components/ExifDataViewer.vue') },
  { path: '/svg-optimizer', name: 'SVG Optimizer', component: () => import('@/components/SVGOptimizer.vue') },
  { path: '/jsonpath-tester', name: 'JSON Path Tester', component: () => import('@/components/JSONPathTester.vue') },
  { path: '/regex-tester', name: 'Regex Tester', component: () => import('@/components/RegexTester.vue') },
  { path: '/regex-generator', name: 'Regex Generator', component: () => import('@/components/RegexGenerator.vue') },
  { path: '/api-response-tester', name: 'API Response Tester', component: () => import('@/components/ApiResponseTester.vue') },
  { path: '/curl-command-generator', name: 'Curl Command Generator', component: () => import('@/components/CurlCommandGenerator.vue') },
  { path: '/websocket-tester', name: 'WebSocket Tester', component: () => import('@/components/WebSocketTester.vue') },
  { path: '/cron-job-generator', name: 'Cron Job Generator', component: () => import('@/components/CronJobGenerator.vue') },
  { path: '/htaccess-redirect-generator', name: 'Htaccess Redirect Generator', component: () => import('@/components/HtaccessRedirectGenerator.vue') },
  { path: '/http-request-viewer', name: 'HTTP Request Viewer', component: () => import('@/components/HttpRequestViewer.vue') },
  { path: '/jwt-decoder', name: 'JWT Decoder', component: () => import('@/components/JwtDecoder.vue') },
  { path: '/api-request-builder', name: 'API Request Builder', component: () => import('@/components/ApiRequestBuilder.vue') },
  { path: '/webhook-tester', name: 'Webhook Tester', component: () => import('@/components/WebhookTester.vue') },
  { path: '/css-animation-generator', name: 'CSS Animation Generator', component: () => import('@/components/CssAnimationGenerator.vue') },
  { path: '/cors-tester', name: 'CORS Tester', component: () => import('@/components/CorsTester.vue') },
  { path: '/unix-timestamp-generator', name: 'Unix Timestamp Generator', component: () => import('@/components/UnixTimestampGenerator.vue') },
  { path: '/unicode-character-lookup', name: 'Unicode Character Lookup', component: () => import('@/components/UnicodeCharacterLookup.vue') },
  { path: '/browser-fingerprinting-tool', name: 'Browser Fingerprinting Tool', component: () => import('@/components/BrowserFingerprintingTool.vue') },
  { path: '/screen-resolution-tester', name: 'Screen Resolution Tester', component: () => import('@/components/ScreenResolutionTester.vue') },
  { path: '/time-zone-converter', name: 'Time Zone Converter', component: () => import('@/components/TimeZoneConverter.vue') },
  { path: '/unit-converter', name: 'Unit Converter', component: () => import('@/components/UnitConverter.vue') },
  { path: '/sql-query-generator', name: 'SQL Query Generator', component: () => import('@/components/SQLQueryGenerator.vue') },
  { path: '/database-schema-designer', name: 'Database Schema Designer', component: () => import('@/components/DatabaseSchemaDesigner.vue') },
  { path: '/mongodb-query-builder', name: 'MongoDB Query Builder', component: () => import('@/components/MongoDBQueryBuilder.vue') },
  { path: '/sqlite-query-builder', name: 'SQLite Query Builder', component: () => import('@/components/SQLiteQueryBuilder.vue') },
  { path: '/postgresql-query-builder', name: 'PostgreSQL Query Builder', component: () => import('@/components/PostgreSQLQueryBuilder.vue') },
  { path: '/svg-to-css-converter', name: 'SVG to CSS Converter', component: () => import('@/components/SVGToCSSConverter.vue') },
  { path: '/font-pairing-tool', name: 'Font Pairing Tool', component: () => import('@/components/FontPairingTool.vue') },
  { path: '/accessibility-contrast-checker', name: 'Accessibility Contrast Checker', component: () => import('@/components/AccessibilityContrastChecker.vue') },
  { path: '/css-clip-path-generator', name: 'CSS Clip Path Generator', component: () => import('@/components/CSSClipPathGenerator.vue') },
  { path: '/subdomain-scanner', name: 'Subdomain Scanner', component: () => import('@/components/SubdomainScanner.vue') },
  { path: '/csp-generator', name: 'CSP Generator', component: () => import('@/components/CSPGenerator.vue') },
  { path: '/json-xml-converter', name: 'JsonXmlConverter', component: () => import('@/components/JsonXmlConverter.vue') }
  // Add other tool routes here
];

const router = createRouter({
  history: createWebHistory(process.env.BASE_URL),
  routes
});

export default router;
