name: Node.js CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 19.x

    - name: Install dependencies in frontend
      run: cd frontend && npm install

    - name: Install dependencies in server
      run: cd server && npm install

    - name: Build frontend project
      run: cd frontend && npm run build

  build-macos:
    name: Build on macOS
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 19.x

    - name: Install dependencies in frontend
      run: cd frontend && npm install

    - name: Install dependencies in server
      run: cd server && npm install

    - name: Build frontend project
      run: cd frontend && npm run build

  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 19.x

    - name: Install dependencies in frontend
      run: cd frontend && npm install

    - name: Install dependencies in server
      run: cd server && npm install

    - name: Build frontend project
      run: cd frontend && npm run build
